### ISSUE TITLE
The package fails the build with new archiver version

### ISSUE THREAD

**Issue by polluxx** [nickalie/go-binwrapper#1]
Hi, not sure if that was fixed, but looks like not:)
After upgrading to the archiver 3.1 version, they look like removed `SupportedFormats` field, which is used in `/binwrapper.go:341:20`.

Pasting also the second error trace line:
`binwrapper.go:354:12: arc.Open undefined (type archiver.Archiver has no field or method Open)`
Seems like the same problem.

Could you tell which version of the archiver is working with the package?

**Comment by mjarkk** [comment]
Same problem here i've made a fix for it here: https://github.com/mjarkk/go-binwrapper

**Comment by nickalie** [comment]
@mjarkk, that's great! Could you please create PR?

**Comment by mjarkk** [comment]
I'll see if i can transform everything back to only include the fix

**Comment by nickalie** [comment]
Thanks @mjarkk!
Fixed by https://github.com/nickalie/go-binwrapper/pull/2
